//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackjack.BlackjackServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/BlackjackContracts")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Blackjack.BlackjackServiceReference.Card.FaceType FaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaceJSStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Blackjack.BlackjackServiceReference.Card.SuitType SuitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuitJSStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Blackjack.BlackjackServiceReference.Card.FaceType Face {
            get {
                return this.FaceField;
            }
            set {
                if ((this.FaceField.Equals(value) != true)) {
                    this.FaceField = value;
                    this.RaisePropertyChanged("Face");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaceJSString {
            get {
                return this.FaceJSStringField;
            }
            set {
                if ((object.ReferenceEquals(this.FaceJSStringField, value) != true)) {
                    this.FaceJSStringField = value;
                    this.RaisePropertyChanged("FaceJSString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Blackjack.BlackjackServiceReference.Card.SuitType Suit {
            get {
                return this.SuitField;
            }
            set {
                if ((this.SuitField.Equals(value) != true)) {
                    this.SuitField = value;
                    this.RaisePropertyChanged("Suit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuitJSString {
            get {
                return this.SuitJSStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SuitJSStringField, value) != true)) {
                    this.SuitJSStringField = value;
                    this.RaisePropertyChanged("SuitJSString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Card.FaceType", Namespace="http://schemas.datacontract.org/2004/07/BlackjackContracts")]
        public enum FaceType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ace = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Two = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Three = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Four = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Five = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Six = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Seven = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Eight = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Nine = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ten = 9,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Jack = 10,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Queen = 11,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            King = 12,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Card.SuitType", Namespace="http://schemas.datacontract.org/2004/07/BlackjackContracts")]
        public enum SuitType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Club = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Diamond = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Heart = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Spade = 3,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BlackjackServiceReference.IBlackjackService")]
    public interface IBlackjackService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/GetShuffledDeck", ReplyAction="http://tempuri.org/IBlackjackService/GetShuffledDeckResponse")]
        Blackjack.BlackjackServiceReference.Card[] GetShuffledDeck();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/GetPossibleValues", ReplyAction="http://tempuri.org/IBlackjackService/GetPossibleValuesResponse")]
        int[] GetPossibleValues(Blackjack.BlackjackServiceReference.Card[] Hand);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlackjackServiceChannel : Blackjack.BlackjackServiceReference.IBlackjackService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlackjackServiceClient : System.ServiceModel.ClientBase<Blackjack.BlackjackServiceReference.IBlackjackService>, Blackjack.BlackjackServiceReference.IBlackjackService {
        
        public BlackjackServiceClient() {
        }
        
        public BlackjackServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlackjackServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackjackServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackjackServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Blackjack.BlackjackServiceReference.Card[] GetShuffledDeck() {
            return base.Channel.GetShuffledDeck();
        }
        
        public int[] GetPossibleValues(Blackjack.BlackjackServiceReference.Card[] Hand) {
            return base.Channel.GetPossibleValues(Hand);
        }
    }
}
