//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackjack.UI.BlackjackServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartingHands", Namespace="http://schemas.datacontract.org/2004/07/Blackjack.Contracts.Entities")]
    [System.SerializableAttribute()]
    public partial class StartingHands : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Blackjack.UI.BlackjackServiceReference.Card[] DealerHandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Blackjack.UI.BlackjackServiceReference.Card[][] PlayerHandsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Blackjack.UI.BlackjackServiceReference.Card[] DealerHand {
            get {
                return this.DealerHandField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerHandField, value) != true)) {
                    this.DealerHandField = value;
                    this.RaisePropertyChanged("DealerHand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Blackjack.UI.BlackjackServiceReference.Card[][] PlayerHands {
            get {
                return this.PlayerHandsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerHandsField, value) != true)) {
                    this.PlayerHandsField = value;
                    this.RaisePropertyChanged("PlayerHands");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/Blackjack.Contracts.Entities")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Blackjack.UI.BlackjackServiceReference.CardFace FaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Blackjack.UI.BlackjackServiceReference.CardSuit SuitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Blackjack.UI.BlackjackServiceReference.CardFace Face {
            get {
                return this.FaceField;
            }
            set {
                if ((this.FaceField.Equals(value) != true)) {
                    this.FaceField = value;
                    this.RaisePropertyChanged("Face");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Blackjack.UI.BlackjackServiceReference.CardSuit Suit {
            get {
                return this.SuitField;
            }
            set {
                if ((this.SuitField.Equals(value) != true)) {
                    this.SuitField = value;
                    this.RaisePropertyChanged("Suit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardFace", Namespace="http://schemas.datacontract.org/2004/07/Blackjack.Contracts.Entities")]
    public enum CardFace : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ace = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Two = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Three = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Four = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Five = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Six = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Seven = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eight = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nine = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ten = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jack = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Queen = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        King = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardSuit", Namespace="http://schemas.datacontract.org/2004/07/Blackjack.Contracts.Entities")]
    public enum CardSuit : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Clubs = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Diamonds = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hearts = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spades = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BlackjackServiceReference.IBlackjackService")]
    public interface IBlackjackService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/StartGame", ReplyAction="http://tempuri.org/IBlackjackService/StartGameResponse")]
        Blackjack.UI.BlackjackServiceReference.StartingHands StartGame(int players);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/GiveCardToPlayer", ReplyAction="http://tempuri.org/IBlackjackService/GiveCardToPlayerResponse")]
        Blackjack.UI.BlackjackServiceReference.Card GiveCardToPlayer(int playerIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/GiveCardToDealer", ReplyAction="http://tempuri.org/IBlackjackService/GiveCardToDealerResponse")]
        Blackjack.UI.BlackjackServiceReference.Card GiveCardToDealer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/GetDealerPossibleValues", ReplyAction="http://tempuri.org/IBlackjackService/GetDealerPossibleValuesResponse")]
        int[] GetDealerPossibleValues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/GetPlayerPossibleValues", ReplyAction="http://tempuri.org/IBlackjackService/GetPlayerPossibleValuesResponse")]
        int[] GetPlayerPossibleValues(int playerIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/PlayerHasBlackjack", ReplyAction="http://tempuri.org/IBlackjackService/PlayerHasBlackjackResponse")]
        bool PlayerHasBlackjack(int playerIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/PlayerLost", ReplyAction="http://tempuri.org/IBlackjackService/PlayerLostResponse")]
        bool PlayerLost(int playerIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/DealerStand", ReplyAction="http://tempuri.org/IBlackjackService/DealerStandResponse")]
        bool DealerStand();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/DealerHasBlackjack", ReplyAction="http://tempuri.org/IBlackjackService/DealerHasBlackjackResponse")]
        bool DealerHasBlackjack();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/PlayerWins", ReplyAction="http://tempuri.org/IBlackjackService/PlayerWinsResponse")]
        int PlayerWins(int playerIndex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlackjackServiceChannel : Blackjack.UI.BlackjackServiceReference.IBlackjackService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlackjackServiceClient : System.ServiceModel.ClientBase<Blackjack.UI.BlackjackServiceReference.IBlackjackService>, Blackjack.UI.BlackjackServiceReference.IBlackjackService {
        
        public BlackjackServiceClient() {
        }
        
        public BlackjackServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlackjackServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackjackServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackjackServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Blackjack.UI.BlackjackServiceReference.StartingHands StartGame(int players) {
            return base.Channel.StartGame(players);
        }
        
        public Blackjack.UI.BlackjackServiceReference.Card GiveCardToPlayer(int playerIndex) {
            return base.Channel.GiveCardToPlayer(playerIndex);
        }
        
        public Blackjack.UI.BlackjackServiceReference.Card GiveCardToDealer() {
            return base.Channel.GiveCardToDealer();
        }
        
        public int[] GetDealerPossibleValues() {
            return base.Channel.GetDealerPossibleValues();
        }
        
        public int[] GetPlayerPossibleValues(int playerIndex) {
            return base.Channel.GetPlayerPossibleValues(playerIndex);
        }
        
        public bool PlayerHasBlackjack(int playerIndex) {
            return base.Channel.PlayerHasBlackjack(playerIndex);
        }
        
        public bool PlayerLost(int playerIndex) {
            return base.Channel.PlayerLost(playerIndex);
        }
        
        public bool DealerStand() {
            return base.Channel.DealerStand();
        }
        
        public bool DealerHasBlackjack() {
            return base.Channel.DealerHasBlackjack();
        }
        
        public int PlayerWins(int playerIndex) {
            return base.Channel.PlayerWins(playerIndex);
        }
    }
}
